### ISSUE TITLE
Chatroom branch doesn't build with webpack

### ISSUE THREAD

**Issue by yawkity** [DIALUPSTUFF/DIALUPSITE#10]
Socket.io dependent libraries won't work when bundling application with webpack-dev-server, but does when calling "npm start":
<img width="1237" alt="screen shot 2016-12-09 at 12 40 38 pm" src="https://cloud.githubusercontent.com/assets/3255833/21058615/cef6726a-be0c-11e6-9160-0b9b09a958f4.png">

Even when changing the webpack.config.js port to 3000 as defined in the socket.io script of index.html, you still receive an error. This might be a fix: http://jlongster.com/Backend-Apps-with-Webpack--Part-I#Getting-Started

**Comment by bomanimc** [comment]
Is this still an issue?

**Comment by bomanimc** [comment]
This makes sense. `webpack-dev-server` is totally separate from the Node/Express server where the socket.io code lives. `webpack-dev-server` only deals with the client-side files. It's a bit like using SimpleHTTPServer inside of a Node project. 

We could looking into using `reload` or `nodemon` for reloading that also triggers when server-side code is changed. We can add separate issues for that.
