### ISSUE TITLE
Error when loading fonts

### ISSUE THREAD

**Issue by yawkity** [DialUpStuff/DialUpSite#11]
Chrome console reports an error upon loading the ArialRoundedMTBold font:

<img width="1280" alt="screen shot 2016-12-09 at 1 06 03 pm" src="https://cloud.githubusercontent.com/assets/3255833/21059434/5c8a4a2c-be10-11e6-948c-65ce81846228.png">

**Comment by bomanimc** [comment]
Fixed in #22
