### ISSUE TITLE
Add Documentation for Magazine Releases

### ISSUE THREAD

**Issue by yawkity** [DIALUPSTUFF/DIALUPSITE#13]
No documentation on the basic operations needed to release a mag, and push the site to staging or prod. Here are a few notes on the release process:

<img width="583" alt="screen shot 2016-12-09 at 1 35 38 pm" src="https://cloud.githubusercontent.com/assets/3255833/21060279/88cd0440-be14-11e6-94b6-5c03408dc946.png">

This documentation should be added the Github Readme

**Comment by bomanimc** [comment]
@yawkity I've added some documentation on deploying to staging here. Still need to add prod deployment docs though.

**Comment by bomanimc** [comment]
Added deployment guides in CODINGRULES repo. Still need to add mag release guidelines.
