### ISSUE TITLE
Remove Unused colors.json Files

### ISSUE THREAD

**Issue by yawkity** [DIALUPSTUFF/DIALUPSITE#17]
Added code to give gradient background colors to the mag reader experience, but it’s never been used so it should be deleted and statically set to black.

**Comment by yawkity** [comment]
@bomanimc I think this can be addressed by just removing the file right? No work really has to be done for this

**Comment by bomanimc** [comment]
There would be some code changes to know out when we re-add the old magreader to the site for the short term. I'll do this one.

**Comment by bomanimc** [comment]
Deciding not to change since we will ideally delete this stuff within about a month, and should prioritize time to other areas.
