### ISSUE TITLE
Improve Hacky Reader Infrastructure

### ISSUE THREAD

**Issue by yawkity** [DIALUPSTUFF/DIALUPSITE#18]
A lot of hacky code to direct the current mag viewers (Photoswipe and Pulp Viewer) to render the correct mag given a URL. Using photoswipe on Safari (Desktop). Inconsistent (and lamer) reader experience on Safari. No two page spreads, etc.

*Note*
This might not be high priority if we're working on a new magazine reader

**Comment by bomanimc** [comment]
Since new reader is in the work, I think we can go ahead close this and leave comments on the new reader repo.
