### ISSUE TITLE
Remove audio tracks from background videos

### ISSUE THREAD

**Issue by bomanimc** [DIALUPSTUFF/DIALUPSITE#28]
`ffmpeg -i input_file.mp4 -vcodec copy -an output_file.mp4` to remove all audio tracks from an mp4.  `brew install ffmpeg` to get this command.

**Comment by yawkity** [comment]
Was this already committed to master?

**Comment by bomanimc** [comment]
@yawkity Haven't done this yet, but would be cool to do.
