### ISSUE TITLE
Truncate long usernames to a specific # of characters

### ISSUE THREAD

**Issue by bomanimc** [DIALUPSTUFF/DIALUPSITE#60]

**Comment by yawkity** [comment]
Shouldn't be too hard, just adding a new clause to the switch statement.

**Comment by MagicWilliams** [comment]
@teahb took care of this juuuu heeaaarrrddd

**Comment by yawkity** [comment]
@MagicWilliams Does typing in "/setname test test" give an error message? I tried on the heroku site but I might have messed something up and broke it

**Comment by bomanimc** [comment]
Fixed by @teahb in https://github.com/DIALUPSTUFF/DIALUPSITE/commit/ce6efb44d4e5fbecd9f7fe3d0aa2cbef66c42ba1
