### ISSUE TITLE
Implement a mobile version of the Radio Page for MVP

### ISSUE THREAD

**Issue by bomanimc** [DIALUPSTUFF/DIALUPSITE#63]
Something like this rough cut should be fine. <img width="369" alt="screen shot 2017-01-31 at 2 45 43 am" src="https://cloud.githubusercontent.com/assets/6589909/22457841/632b5b6e-e75f-11e6-814f-460671bd53ac.png">

**Comment by bomanimc** [comment]
One issue I for see is that mobile browsers might not allow for autoplaying. Currently in desktop browsers, it autoplays the stream and the button just controls the volume (0 volume when it’s ‘paused’). We do this because when you pause the stream after playing it initially, it gets off-time with the live version. 

You might need to update the logic for the button component so that the first time it’s clicked it actually plays the stream, and subsequent clicks control volume in the same way as it does for the browser. 

If that doesn't work, we might have to just somehow reinstantiate the whole player every time it's played so it's always in sync with the live stream.

**Comment by yawkity** [comment]
@bomanimc Once we get the stream working we can better debug this issue
