### ISSUE TITLE
Design & Implement Application Bot UX

### ISSUE THREAD

**Issue by bomanimc** [DIALUPSTUFF/DIALUPSITE#65]
How do we want the application bot to onboard new users about the command framework? How should it be design? Should notifications about color changes, etc show up as messages or just short details in between messages?

**Comment by yawkity** [comment]
**Onboarding new users**

I feel we should welcome new users that join the chatroom with a client-side description and overview of commands available. We should also add a "/help" command to show the message again and maybe integrate "Type /help for more info" somewhere into the UI.

**Comment by yawkity** [comment]
#66
