### ISSUE TITLE
Update Stream Button logic to play on Desktop and Mobile

### ISSUE THREAD

**Issue by sehmon** [DIALUPSTUFF/DIALUPSITE#80]
"One issue I for see is that mobile browsers might not allow for autoplaying. Currently in desktop browsers, it autoplays the stream and the button just controls the volume (0 volume when it’s ‘paused’). We do this because when you pause the stream after playing it initially, it gets off-time with the live version.

You might need to update the logic for the button component so that the first time it’s clicked it actually plays the stream, and subsequent clicks control volume in the same way as it does for the browser.

If that doesn't work, we might have to just somehow reinstantiate the whole player every time it's played so it's always in sync with the live stream."

- @bomanimc

**Comment by bomanimc** [comment]
Remaining issue is that the mobile version pauses and doesn't stay in sync with live version of the stream.
