### ISSUE TITLE
Setting username changes the name of all other user's messages that had the same name in the past

### ISSUE THREAD

**Issue by bomanimc** [DIALUPSTUFF/DIALUPSITE#86]
I changed my name here
<img width="522" alt="screen shot 2017-02-15 at 3 10 14 pm" src="https://cloud.githubusercontent.com/assets/6589909/22995565/f992ad36-f390-11e6-8d62-cddde9f57913.png">

and this message that must have been sent to someone that had User 1 as a name also changed.
<img width="534" alt="screen shot 2017-02-15 at 3 10 06 pm" src="https://cloud.githubusercontent.com/assets/6589909/22995564/f98b901e-f390-11e6-97dd-5d3c9bde11d0.png">

One bandaid solution could be use the random usernames so there's less likeliness that someone has had the same name. Another one might be to not change all of the names in the DB when people switch names, and just change their names moving forward. A bit of both might be best.

**Comment by yawkity** [comment]
(Lame) fix for this in #82

**Comment by bomanimc** [comment]
@yawkity Do we want to have the setname go back through the DB and change all of the users old messages though btw? That's a lot of DB operations that we're opening ourselves up to.

**Comment by yawkity** [comment]
were already sending the "____ changed their name to ______" messages right? I feel that should be enough

**Comment by yawkity** [comment]
#87
